apiVersion: keptn.sh/v1
kind: GitPromotionConfig
metadata:
  name: ortelius-podtato-head-test
spec:
  strategy: flat-pr
  nextStage: prod
  lastStage: stag
  autoApprove: false
  target:
    repo: https://github.com/ortelius/ortelius-kubernetes
    secret: github
    provider: github
  paths:
    - source: kube-infra/kustomize/podtato-head/podtato-head/envs/stag/settings.yaml
      target: kube-infra/kustomize/podtato-head/podtato-head/envs/prod/settings.yaml
