apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metadata:
  name: "ortelius"
spec:
  stages:
    - name: "load"
      sequences:
      - name: "smoke"
        tasks:
        - name: "smoke-test"
      - name: "test"
        triggeredOn:
          - event: "load.smoke.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "load-test"
        - name: "evaluation"
          properties:
            timeframe: 5m
        - name: "git-promotion"
        - name: "catalog"
    - name: "int"
      sequences:
      - name: "test"
        triggeredOn:
          - event: "load.test.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "api-test"
        - name: "trace-test"
        - name: "evaluation"
          properties:
            timeframe: 5m
        - name: "git-promotion"
        - name: "catalog"
    - name: "qa"
      sequences:
      - name: "test"
        triggeredOn:
          - event: "int.test.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "api-test"
        - name: "trace-test"
        - name: "evaluation"
          properties:
            timeframe: 5m
        - name: "git-promotion"
        - name: "catalog"
    - name: "stag"
      sequences:
      - name: "test"
        triggeredOn:
          - event: "qa.test.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "api-test"
        - name: "evaluation"
          properties:
            timeframe: 5m
        - name: "git-promotion"  
        - name: "catalog"
    - name: "prod"
      sequences:
      - name: "test"
        triggeredOn:
          - event: "stag.test.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "catalog"
