apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - url: https://hooks.slack.com/services/{{.env.secret_slackwebhook_token}}
          payload: >-
            payload={   "channel" : "{{.data.project}}--{{.data.service}}",  "username" : "keptn",   "blocks": [    {      "type" : "section",      "text" : {        "type": "mrkdwn",        "text" : "*Keptn Evaluation finished:* {{.data.result}} ({{.data.evaluation.score}} / 100)"      }    },    {      "type" : "section",      "text" : {        "type": "mrkdwn",        "text" : "*Project:* {{.data.project}}\n*Stage:* {{.data.stage}}\n*Service:* {{.data.service}}\n*Details:* {{.env.secret_slackwebhook_bridgeUrl}}/bridge/evaluation/{{.shkeptncontext}}"      }    }  ]}
          headers: []
          method: POST
      envFrom:
        - name: secret_slackwebhook_token
          secretRef:
            name: slackwebhook
            key: token
      subscriptionID: f450bb87-592a-495e-8543-a44c1221fcb3
      sendFinished: false
      sendStarted: false
